# docker-compose.yml
services:
  postgres_test:
    image: pgvector/pgvector:pg16
    container_name: welcomecraft_postgres_test
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - '5433:5432'
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - ./scripts/db-init/01-init-extensions.sql:/docker-entrypoint-initdb.d/01-init-extensions.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d testdb" ]
      interval: 5s
      timeout: 5s
      retries: 5